
from selenium import webdriver as wd
import time
from selenium.webdriver.support.ui import Select

url = input('Please enter Newegg URL: ')
username = input('Please enter Email: ')
passw = input('Please enter Password: ')

if username == 'guest' and passw == 'guest':
    print('------------------------------')
    print('Shipping Details')
    print('------------------------------')
    guestname = input('Please enter First Name: ')
    guestlast = input('Please enter Last Name: ')
    guestaddy = input('Please enter Shipping Address: ')
    guestaddy2 = input('Please enter Shipping Address 2 (Optional): ')
    guestcity = input('Please enter City: ')
    gueststate = input('Please enter State: ')
    guestzip = input('Please enter Zipcode: ')
    guestphone = input('Please enter Phone #: ')
    guestemail = input('Please enter Email Address for Order Notification: ')
    print('------------------------------')
    print('Credit/Debit Card Info:')
    print('------------------------------')
    guestcardname = input('Please enter Cardholder Name: ')
    guestcardnumber = input('Please enter Card Number: ')
    guestcardaddress = input('Please enter Billing Address: ')
    guestcardaddress2 = input('Please enter Billing Address 2 (Optional): ')
    guestcardexpiration = input('Please enter Expiration Month: ')
    guestcardexpirationyear = input('Please enter Expiration Year: ')
else:
    print('------------------------------')
    cvv = input('Please enter CVV: ')
    print('------------------------------')


driver = wd.Chrome(executable_path=r'C:\Users\User1\Desktop\chromedriver.exe')
driver.get(url)
driver.maximize_window()

outofstock = 'OUT OF STOCK.'
src = driver.page_source


while outofstock in src:
    driver.refresh()
    time.sleep(3)

if username == 'guest' and passw == 'guest':
    click = driver.find_element_by_xpath('//*[@id="ProductBuy"]/div/div[2]/button')
    click.click()
    driver.implicitly_wait(3)
    click0 = driver.find_element_by_xpath('//*[@id="modal-intermediary"]/div/div/div/div[3]/button[1]')
    click0.click()  
    driver.implicitly_wait(3)
    click1 = driver.find_element_by_xpath('//*[@id="modal-intermediary"]/div/div/div[2]/div[2]/button[2]')
    click1.click()    
    driver.implicitly_wait(3)
    click2 = driver.find_element_by_xpath('//*[@id="app"]/div[1]/section/div/div/form/div[2]/div[3]/div/div/div[3]/div/button')
    click2.click()
    driver.implicitly_wait(3)
    guestclick = driver.find_element_by_xpath('//*[@id="app"]/div/div[2]/div[2]/div/div/div[1]/form[2]/div[2]/div/button')
    guestclick.click()
    guestclickaddy = driver.find_element_by_xpath('//*[@id="shippingItemCell"]/div/div[2]/div[2]/div/div[2]/div[2]/div/div')
    guestclickaddy.click()
    driver.implicitly_wait(3)
    firstnamefill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[1]/input')
    firstnamefill.send_keys(str(guestname))
    lastnamefill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[2]/input')
    lastnamefill.send_keys(str(guestlast))
    guestaddyfill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[6]/input')
    guestaddyfill.send_keys(str(guestaddy))
    guestaddyfill2 = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[7]/input')
    guestaddyfill2.send_keys(str(guestaddy2))
    guestzipfill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[10]/input')
    guestzipfill.send_keys(str(guestzip))
    guestphonefill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[12]/input')
    guestphonefill.send_keys(str(guestphone))
    guestcityfill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[8]/input')
    guestcityfill.send_keys(str(guestcity))
    guestemailfill = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[15]/input')
    guestemailfill.send_keys(str(guestemail))
    driver.implicitly_wait(3)
    sia = str(gueststate.upper())
    gueststatefill = Select(driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[2]/form/div[2]/div[9]/label[2]/select'))
    gueststatefill.select_by_visible_text(sia)
    driver.implicitly_wait(3)
    guestsave = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[3]/button[2]')
    guestsave.click()
    driver.implicitly_wait(100)
    time.sleep(4)
    useaddress = driver.find_element_by_xpath('//*[@id="app"]/div/div/div/div/div[3]/button[2]')
    useaddress.click()
    driver.implicitly_wait(100)
    time.sleep(4)
    conttodelivery = driver.find_element_by_xpath('//*[@id="shippingItemCell"]/div/div[3]/button')
    conttodelivery.click()
    
    driver.implicitly_wait(100)
    topayment = driver.find_element_by_xpath('//*[@id="deliveryItemCell"]/div/div[3]/button')
    topayment.click()

    driver.implicitly_wait(100)
    addnewcard = driver.find_element_by_xpath('//*[@id="paymentItemCell"]/div/div[2]/div/div[2]/div[2]/div[3]/div/div')

else:
#clicks, regular username and password
    click = driver.find_element_by_xpath('//*[@id="ProductBuy"]/div/div[2]/button')
    click.click()
    driver.implicitly_wait(3)
    click0 = driver.find_element_by_xpath('//*[@id="modal-intermediary"]/div/div/div/div[3]/button[1]')
    click0.click()
    driver.implicitly_wait(3)
    click1 = driver.find_element_by_xpath('//*[@id="modal-intermediary"]/div/div/div[2]/div[2]/button[2]')
    click1.click()
    driver.implicitly_wait(3)
    click2 = driver.find_element_by_xpath('//*[@id="app"]/div[1]/section/div/div/form/div[2]/div[3]/div/div/div[3]/div/button')
    click2.click()
    driver.implicitly_wait(3)
    email = driver.find_element_by_xpath('//*[@id="labeled-input-signEmail"]')
    email.send_keys(str(username))
    driver.implicitly_wait(3)
    click3 = driver.find_element_by_xpath('//*[@id="signInSubmit"]')
    click3.click()
    driver.implicitly_wait(3)
    password = driver.find_element_by_xpath('//*[@id="labeled-input-password"]')
    password.send_keys(str(passw))
    driver.implicitly_wait(3)
    click4 = driver.find_element_by_xpath('//*[@id="signInSubmit"]')
    click4.click()



    driver.implicitly_wait(3)
    todelivery = driver.find_element_by_xpath('//*[@id="shippingItemCell"]/div/div[3]/button')
    todelivery.click()
    driver.implicitly_wait(3)
    topayment = driver.find_element_by_xpath('//*[@id="deliveryItemCell"]/div/div[3]/button')
    topayment.click()
    tocvv = driver.find_element_by_xpath('//*[@id="paymentItemCell"]/div/div[2]/div/div[3]/div[2]/div[2]/div[1]/div/label/div[3]/input')
    tocvv.send_keys(str(cvv))
    driver.implicitly_wait(3)
    torevieworder = driver.find_element_by_xpath('//*[@id="paymentItemCell"]/div/div[3]/button')
    torevieworder.click()

    toplaceorder = driver.find_element_by_xpath('//*[@id="btnCreditCard"]')
